<?php

namespace Database\Seeders;

use App\Models\Theme;
use App\Services\ThemeService;
use Illuminate\Database\Seeder;

class ThemeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $defaultPalette = ThemeService::getDefaultColorPalette();

        $themes = [
            [
                'name' => 'Default (Original)',
                'slug' => 'default-original',
                'type' => 'light',
                'is_default' => true,
                'is_active' => true,
                'colors' => $defaultPalette,
            ],
            [
                'name' => 'Ocean Light',
                'slug' => 'ocean-light',
                'type' => 'light',
                'is_default' => false,
                'is_active' => true,
                'colors' => array_merge($defaultPalette, [
                    'bg_page' => '#FFFFFF',
                    'bg_surface' => '#F8FAFC',
                    'border_color' => '#E2E8F0',
                    'text_primary' => '#1E293B',
                    'text_secondary' => '#64748B',
                    'text_heading' => '#0F172A',
                    'text_link' => '#2563EB',
                    'text_link_hover' => '#1D4ED8',
                    'navbar_bg' => '#FFFFFF',
                    'navbar_text' => '#1E293B',
                    'navbar_active' => '#2563EB',
                    'btn_primary_bg' => '#2563EB',
                    'btn_primary_hover' => '#1D4ED8',
                    'card_bg' => '#F8FAFC',
                    'card_border' => '#E2E8F0',
                    'table_header_bg' => '#F1F5F9',
                    'table_header_text' => '#475569',
                    'table_row_bg' => '#FFFFFF',
                    'table_row_alt' => '#F8FAFC',
                    'input_bg' => '#FFFFFF',
                    'input_border' => '#CBD5E1',
                    'input_focus' => '#2563EB',
                    'icon_color' => '#2563EB',
                ]),
            ],
            [
                'name' => 'Emerald Light',
                'slug' => 'emerald-light',
                'type' => 'light',
                'is_default' => false,
                'is_active' => true,
                'colors' => array_merge($defaultPalette, [
                    'bg_page' => '#FFFFFF',
                    'bg_surface' => '#F0FDF4',
                    'border_color' => '#D1FAE5',
                    'text_primary' => '#1F2937',
                    'text_secondary' => '#6B7280',
                    'text_heading' => '#065F46',
                    'text_link' => '#059669',
                    'text_link_hover' => '#047857',
                    'navbar_bg' => '#FFFFFF',
                    'navbar_text' => '#1F2937',
                    'navbar_active' => '#059669',
                    'btn_primary_bg' => '#059669',
                    'btn_primary_hover' => '#047857',
                    'card_bg' => '#F0FDF4',
                    'card_border' => '#D1FAE5',
                    'table_header_bg' => '#ECFDF5',
                    'table_header_text' => '#047857',
                    'table_row_bg' => '#FFFFFF',
                    'table_row_alt' => '#F0FDF4',
                    'input_bg' => '#FFFFFF',
                    'input_border' => '#A7F3D0',
                    'input_focus' => '#059669',
                    'icon_color' => '#059669',
                    'footer_bg' => '#064E3B',
                    'footer_text' => '#A7F3D0',
                ]),
            ],
            [
                'name' => 'Sunset Light',
                'slug' => 'sunset-light',
                'type' => 'light',
                'is_default' => false,
                'is_active' => true,
                'colors' => array_merge($defaultPalette, [
                    'bg_page' => '#FFFFFF',
                    'bg_surface' => '#FFF7ED',
                    'border_color' => '#FED7AA',
                    'text_primary' => '#292524',
                    'text_secondary' => '#78716C',
                    'text_heading' => '#7C2D12',
                    'text_link' => '#EA580C',
                    'text_link_hover' => '#C2410C',
                    'navbar_bg' => '#FFFFFF',
                    'navbar_text' => '#292524',
                    'navbar_active' => '#EA580C',
                    'btn_primary_bg' => '#EA580C',
                    'btn_primary_hover' => '#C2410C',
                    'card_bg' => '#FFF7ED',
                    'card_border' => '#FED7AA',
                    'table_header_bg' => '#FFEDD5',
                    'table_header_text' => '#9A3412',
                    'table_row_bg' => '#FFFFFF',
                    'table_row_alt' => '#FFF7ED',
                    'input_bg' => '#FFFFFF',
                    'input_border' => '#FDBA74',
                    'input_focus' => '#EA580C',
                    'icon_color' => '#EA580C',
                    'footer_bg' => '#431407',
                    'footer_text' => '#FFEDD5',
                ]),
            ],
            [
                'name' => 'Midnight Blue Dark',
                'slug' => 'midnight-blue-dark',
                'type' => 'dark',
                'is_default' => false,
                'is_active' => true,
                'colors' => [
                    'bg_page' => '#0F172A',
                    'bg_surface' => '#1E293B',
                    'border_color' => '#334155',
                    'text_primary' => '#F1F5F9',
                    'text_secondary' => '#94A3B8',
                    'text_heading' => '#F8FAFC',
                    'text_link' => '#3B82F6',
                    'text_link_hover' => '#60A5FA',
                    'navbar_bg' => '#0F172A',
                    'navbar_text' => '#F1F5F9',
                    'navbar_active' => '#3B82F6',
                    'btn_primary_bg' => '#3B82F6',
                    'btn_primary_text' => '#FFFFFF',
                    'btn_primary_hover' => '#2563EB',
                    'btn_secondary_bg' => '#1E293B',
                    'btn_secondary_text' => '#F1F5F9',
                    'btn_secondary_border' => '#475569',
                    'card_bg' => '#1E293B',
                    'card_border' => '#334155',
                    'card_title' => '#F8FAFC',
                    'card_body' => '#CBD5E1',
                    'table_header_bg' => '#1E293B',
                    'table_header_text' => '#94A3B8',
                    'table_row_bg' => '#0F172A',
                    'table_row_alt' => '#172236',
                    'table_row_text' => '#F1F5F9',
                    'table_border' => '#334155',
                    'input_bg' => '#1E293B',
                    'input_border' => '#334155',
                    'input_focus' => '#3B82F6',
                    'input_placeholder' => '#64748B',
                    'badge_success_bg' => '#064E3B',
                    'badge_success_text' => '#A7F3D0',
                    'badge_warning_bg' => '#78350F',
                    'badge_warning_text' => '#FDE68A',
                    'badge_error_bg' => '#7F1D1D',
                    'badge_error_text' => '#FECACA',
                    'badge_info_bg' => '#0C4A6E',
                    'badge_info_text' => '#BAE6FD',
                    'footer_bg' => '#020617',
                    'footer_text' => '#94A3B8',
                    'footer_link_hover' => '#38BDF8',
                    'modal_bg' => '#1E293B',
                    'modal_overlay' => 'rgba(0, 0, 0, 0.75)',
                    'icon_color' => '#3B82F6',
                ],
            ],
            [
                'name' => 'Charcoal Violet Dark',
                'slug' => 'charcoal-violet-dark',
                'type' => 'dark',
                'is_default' => false,
                'is_active' => true,
                'colors' => [
                    'bg_page' => '#18181B',
                    'bg_surface' => '#27272A',
                    'border_color' => '#3F3F46',
                    'text_primary' => '#F4F4F5',
                    'text_secondary' => '#A1A1AA',
                    'text_heading' => '#FAFAFA',
                    'text_link' => '#8B5CF6',
                    'text_link_hover' => '#A78BFA',
                    'navbar_bg' => '#18181B',
                    'navbar_text' => '#F4F4F5',
                    'navbar_active' => '#8B5CF6',
                    'btn_primary_bg' => '#8B5CF6',
                    'btn_primary_text' => '#FFFFFF',
                    'btn_primary_hover' => '#7C3AED',
                    'btn_secondary_bg' => '#27272A',
                    'btn_secondary_text' => '#F4F4F5',
                    'btn_secondary_border' => '#52525B',
                    'card_bg' => '#27272A',
                    'card_border' => '#3F3F46',
                    'card_title' => '#FAFAFA',
                    'card_body' => '#D4D4D8',
                    'table_header_bg' => '#27272A',
                    'table_header_text' => '#A1A1AA',
                    'table_row_bg' => '#18181B',
                    'table_row_alt' => '#202023',
                    'table_row_text' => '#F4F4F5',
                    'table_border' => '#3F3F46',
                    'input_bg' => '#27272A',
                    'input_border' => '#3F3F46',
                    'input_focus' => '#8B5CF6',
                    'input_placeholder' => '#71717A',
                    'badge_success_bg' => '#064E3B',
                    'badge_success_text' => '#A7F3D0',
                    'badge_warning_bg' => '#78350F',
                    'badge_warning_text' => '#FDE68A',
                    'badge_error_bg' => '#7F1D1D',
                    'badge_error_text' => '#FECACA',
                    'badge_info_bg' => '#4C1D95',
                    'badge_info_text' => '#DDD6FE',
                    'footer_bg' => '#09090B',
                    'footer_text' => '#A1A1AA',
                    'footer_link_hover' => '#C4B5FD',
                    'modal_bg' => '#27272A',
                    'modal_overlay' => 'rgba(0, 0, 0, 0.75)',
                    'icon_color' => '#8B5CF6',
                ],
            ],
            [
                'name' => 'Forest Dark',
                'slug' => 'forest-dark',
                'type' => 'dark',
                'is_default' => false,
                'is_active' => true,
                'colors' => [
                    'bg_page' => '#0F1B14',
                    'bg_surface' => '#16241B',
                    'border_color' => '#26382C',
                    'text_primary' => '#ECFDF5',
                    'text_secondary' => '#9CA3AF',
                    'text_heading' => '#F0FDF4',
                    'text_link' => '#22C55E',
                    'text_link_hover' => '#4ADE80',
                    'navbar_bg' => '#0F1B14',
                    'navbar_text' => '#ECFDF5',
                    'navbar_active' => '#22C55E',
                    'btn_primary_bg' => '#22C55E',
                    'btn_primary_text' => '#052E16',
                    'btn_primary_hover' => '#16A34A',
                    'btn_secondary_bg' => '#16241B',
                    'btn_secondary_text' => '#ECFDF5',
                    'btn_secondary_border' => '#26382C',
                    'card_bg' => '#16241B',
                    'card_border' => '#26382C',
                    'card_title' => '#F0FDF4',
                    'card_body' => '#D1FAE5',
                    'table_header_bg' => '#16241B',
                    'table_header_text' => '#A7F3D0',
                    'table_row_bg' => '#0F1B14',
                    'table_row_alt' => '#12201A',
                    'table_row_text' => '#ECFDF5',
                    'table_border' => '#26382C',
                    'input_bg' => '#16241B',
                    'input_border' => '#26382C',
                    'input_focus' => '#22C55E',
                    'input_placeholder' => '#6B7280',
                    'badge_success_bg' => '#064E3B',
                    'badge_success_text' => '#A7F3D0',
                    'badge_warning_bg' => '#78350F',
                    'badge_warning_text' => '#FDE68A',
                    'badge_error_bg' => '#7F1D1D',
                    'badge_error_text' => '#FECACA',
                    'badge_info_bg' => '#065F46',
                    'badge_info_text' => '#A7F3D0',
                    'footer_bg' => '#05120A',
                    'footer_text' => '#9CA3AF',
                    'footer_link_hover' => '#86EFAC',
                    'modal_bg' => '#16241B',
                    'modal_overlay' => 'rgba(0, 0, 0, 0.75)',
                    'icon_color' => '#22C55E',
                ],
            ],
        ];

        foreach ($themes as $themeData) {
            Theme::updateOrCreate(
                ['slug' => $themeData['slug']],
                $themeData
            );
        }
    }
}
